/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto.gdr;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author zxt02
 */
public class FormSalvataggio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormSalvataggio.class.getName());
    private FormGioco fg;
    private GameManager gm1, gm2, gmDaSalvare;
    private boolean write;
    private FormMap fm;
    private String path1, path2;
    private int tipoFile;
    /**
     * Creates new form Salva
     */
    public FormSalvataggio() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();

        btnSalvataggio1.setEnabled(false);
        btnSalvataggio2.setEnabled(false);
    }
    
    public GameManager readCSV(String path){
        GameManager gm = null;
        String dati = null;
        try {
            dati = FileManager.readCSV(path);
        } catch (IOException ex) {
            System.getLogger(FormMenu.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        if(dati !=  null) {
            String[] d = dati.split(",");
            if (d.length >= 15) {
                gm = new GameManager(setPersonaggio(d), setMappa(d), d[4]);
                gm.setDati(Integer.parseInt(d[0]), Integer.parseInt(d[1]), Integer.parseInt(d[2]), d[4], d[5]);
            }
        }
        return gm;
    }
    
    
    public void setWrite(boolean w){
        write = w;
        btnSalvataggio1.setEnabled(false);
        btnSalvataggio2.setEnabled(false);
    }
    
    public Personaggio setPersonaggio(String[] d){
        Personaggio p;
        ArrayList<Integer> dati = new ArrayList<>();
        for(int i = 7; i < d.length; i++){
            dati.add(Integer.parseInt(d[i]));
        }
        if(d[6].equals("cuoco")){
            p = new Cuoco();
        }
        else if(d[6].equals("medico")){
            p = new Medico();
        }
        else{
            p = new Veterano();
        }
        
        p.setDati(dati.get(0), dati.get(1), dati.get(2), dati.get(3), dati.get(4),dati.get(5), dati.get(6), dati.get(7));
        return p;
    }
    
    public Mappa setMappa(String[] d){
        Mappa m;
        if(d[3].equals("Deserto")){
            m = new Deserto();
        }
        else if(d[3].equals("cittaDistrutta")){
            m = new CittaDistrutta();
        }
        else{
            m = new Mare();
        }
        return m;
    }
    
    public void setGameManager(GameManager gm){
        gmDaSalvare = gm;
    }
    
    public void salvaCSV(){
        try {
            gmDaSalvare.salvaCSV(path1);
        } catch (IOException ex) {
            System.getLogger(FormGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public void serializza(){
        try {
            gmDaSalvare.serializza(path2);
        } catch (IOException ex) {
            System.getLogger(FormGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    public void setImages(GameManager gm, JButton btn, JLabel lbl){
        if (gm.getMappa().getNome().equals("deserto")) {
                btn.setIcon(new ImageIcon(getClass().getResource("/images/desertoSimbolo.jpg")));
            } else if (gm.getMappa().getNome().equals("cittaDistrutta")) {
                btn.setIcon(new ImageIcon(getClass().getResource("/images/CDsimbolo.jpg")));
            } else {
                btn.setIcon(new ImageIcon(getClass().getResource("/images/mareSimbolo.jpg")));
            }
            lbl.setText(gm.getNickname());
    }
    
    public void deserializza() throws IOException, FileNotFoundException, ClassNotFoundException{
        File f1 = new File("salvataggio1.ser");
        File f2 = new File("salvataggio2.ser");
        if(f1.length() != 0){
            gm1 = FileManager.deserializza("salvataggio1.ser");
            setImages(gm1, btnSalvataggio1, lblNickname1);
        }
        if(f2.length() != 0){
            gm2 = FileManager.deserializza("salvataggio2.ser");
            setImages(gm2, btnSalvataggio2, lblNickname2);
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvataggio2 = new javax.swing.JButton();
        btnSalvataggio1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCSV = new javax.swing.JButton();
        btnSerializzazione = new javax.swing.JButton();
        lblNickname1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblNickname2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 236, 226));

        btnSalvataggio2.setPreferredSize(new java.awt.Dimension(200, 200));
        btnSalvataggio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvataggio2ActionPerformed(evt);
            }
        });

        btnSalvataggio1.setPreferredSize(new java.awt.Dimension(200, 200));
        btnSalvataggio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvataggio1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Salvataggi");

        btnCSV.setBackground(new java.awt.Color(0, 204, 51));
        btnCSV.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnCSV.setForeground(new java.awt.Color(255, 255, 255));
        btnCSV.setText("CSV");
        btnCSV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCSV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCSV.setPreferredSize(new java.awt.Dimension(150, 50));
        btnCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCSVActionPerformed(evt);
            }
        });

        btnSerializzazione.setBackground(new java.awt.Color(207, 43, 43));
        btnSerializzazione.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnSerializzazione.setForeground(new java.awt.Color(255, 255, 255));
        btnSerializzazione.setText("Serializzazione");
        btnSerializzazione.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSerializzazione.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSerializzazione.setPreferredSize(new java.awt.Dimension(150, 50));
        btnSerializzazione.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSerializzazioneActionPerformed(evt);
            }
        });

        lblNickname1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N

        jLabel3.setText("Nickname");

        jLabel4.setText("Nickname");

        lblNickname2.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(260, 260, 260))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(btnCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(lblNickname1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnSalvataggio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSerializzazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNickname2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnSalvataggio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvataggio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvataggio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblNickname2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSerializzazione, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvataggio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvataggio1ActionPerformed
        path1 = "salvataggio1.csv";
        path2 = "salvataggio1.ser";
        
        if(!write){
            if (gm1 != null) {
                fg = new FormGioco(gm1, this);
                fg.setVisible(true);
            } else {
                fm = new FormMap(this);
                fm.setVisible(true);
            }
        }
        else{
            if(tipoFile == 1) serializza();
            else salvaCSV();
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnSalvataggio1ActionPerformed

    private void btnSalvataggio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvataggio2ActionPerformed
        path1 = "salvataggio2.csv";
        path2 = "salvataggio2.ser";

        if(!write){
            if (gm2 != null) {
                fg = new FormGioco(gm2, this);
                fg.setVisible(true);
            } else {
                fm = new FormMap(this);
                fm.setVisible(true);
            }
        }
        else{
            if(tipoFile == 1) serializza();
            else salvaCSV();
        }
        this.setVisible(false);
    }//GEN-LAST:event_btnSalvataggio2ActionPerformed

    private void btnCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCSVActionPerformed
        btnSalvataggio1.setEnabled(true);
        btnSalvataggio2.setEnabled(true);

        gm1 = readCSV("salvataggio1.csv");
        gm2 = readCSV("salvataggio2.csv");
        if (gm1 != null) {
            setImages(gm1, btnSalvataggio1, lblNickname1);
        }
        if (gm2 != null){
            setImages(gm2, btnSalvataggio2, lblNickname2);
        }
        tipoFile = 2;
    }//GEN-LAST:event_btnCSVActionPerformed

    private void btnSerializzazioneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSerializzazioneActionPerformed
        btnSalvataggio1.setEnabled(true);
        btnSalvataggio2.setEnabled(true);
        
        try {
            deserializza();
        } catch (IOException ex) {
            System.getLogger(FormSalvataggio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (ClassNotFoundException ex) {
            System.getLogger(FormSalvataggio.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        tipoFile = 1;
    }//GEN-LAST:event_btnSerializzazioneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCSV;
    private javax.swing.JButton btnSalvataggio1;
    private javax.swing.JButton btnSalvataggio2;
    private javax.swing.JButton btnSerializzazione;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNickname1;
    private javax.swing.JLabel lblNickname2;
    // End of variables declaration//GEN-END:variables
}
