/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto.gdr;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lin.elena
 */
public class FormGioco extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGioco.class.getName());
    private String nome;
    private GameManager gameManager;
    private String[] time;
    private int tempo;
    private FormSalvataggio fs;
    private String background;

    /**
     * Creates new form FormGioco
     */
    public FormGioco(GameManager gm, FormSalvataggio fs) {
        initComponents();

        this.fs = fs;
        gameManager = gm;
        gameManager.getMappa().setPersonaggio(gameManager.getPersonaggio());

        pgbMappa.setMaximum(30);

        time = new String[4];
        time[0] = "8:00";
        time[1] = "13:00";
        time[2] = "17:00";
        time[3] = "22:00";

        gameManager.setTime(time);
        
        btnCibo.setIcon(new ImageIcon(getClass().getResource("/images/cibo.jpg")));
        btnAcqua.setIcon(new ImageIcon(getClass().getResource("/images/acqua.jpg")));
        btnMedicine.setIcon(new ImageIcon(getClass().getResource("/images/medicine.jpg")));
        
        if(gameManager.getMappa().getNome().equals("deserto")){
            background = "/images/deserto.JPG";
        }
        else if(gameManager.getMappa().getNome().equals("cittaDistrutta")){
            background = "/images/CD.JPG";
        }
        else{
            background = "/images/mare.JPG";
        }
        
        setDati();
    }

    public String esplora() {
        String[] dati = gameManager.esplora().split("1121");
        background = dati[1];
        System.out.println(dati[0] + dati[1]);
        setDati();
        return dati[0];
    }

    public void setDati() {
        lblAcqua.setText("" + gameManager.getNAcqua());
        lblCibo.setText("" + gameManager.getNCibo());
        lblMedicine.setText("" + gameManager.getNMedicine());
        pgbSalute.setMaximum(gameManager.getMaxSalute());
        pgbSalute.setValue(gameManager.getSalute());
        pgbSalute.setStringPainted(true);
        pgbSalute.setString("" + gameManager.getSalute());
        lblFame.setText("" + gameManager.getFame());
        lblSete.setText("" + gameManager.getSete());
        lblAttaco.setText("" + gameManager.getAttaco());
        lblDays.setText("" + gameManager.getDays());
        lblTime.setText(gameManager.getTime());
        pgbMappa.setValue(gameManager.getDays()); 
        lblImage.setIcon(new ImageIcon(getClass().getResource(background)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pgbSalute = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFame = new javax.swing.JLabel();
        lblSete = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAttaco = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDays = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        pgbMappa = new javax.swing.JProgressBar();
        slpEvento = new javax.swing.JScrollPane();
        ttaEvento = new javax.swing.JTextArea();
        btnEsplora = new javax.swing.JButton();
        btnCibo = new javax.swing.JButton();
        lblCibo = new javax.swing.JLabel();
        btnAcqua = new javax.swing.JButton();
        lblAcqua = new javax.swing.JLabel();
        btnMedicine = new javax.swing.JButton();
        lblMedicine = new javax.swing.JLabel();
        btnSalva = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 43, 25));

        pgbSalute.setForeground(new java.awt.Color(204, 0, 0));
        pgbSalute.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Salute");

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("FAME");

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Sete");

        lblFame.setForeground(new java.awt.Color(255, 255, 255));
        lblFame.setText("0");

        lblSete.setForeground(new java.awt.Color(255, 255, 255));
        lblSete.setText("0");

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Attaco");

        lblAttaco.setForeground(new java.awt.Color(255, 255, 255));
        lblAttaco.setText("0");

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 255));
        jLabel6.setText("Days:");

        lblDays.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        lblDays.setForeground(new java.awt.Color(255, 255, 255));
        lblDays.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDays.setText("1");

        lblTime.setFont(new java.awt.Font("MS Gothic", 0, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTime.setText("Time:");

        pgbMappa.setBackground(new java.awt.Color(242, 237, 215));
        pgbMappa.setForeground(new java.awt.Color(232, 188, 24));

        slpEvento.setAutoscrolls(true);

        ttaEvento.setEditable(false);
        ttaEvento.setColumns(20);
        ttaEvento.setLineWrap(true);
        ttaEvento.setRows(5);
        ttaEvento.setText("Start!");
        ttaEvento.setWrapStyleWord(true);
        slpEvento.setViewportView(ttaEvento);

        btnEsplora.setBackground(new java.awt.Color(250, 226, 153));
        btnEsplora.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        btnEsplora.setText("Esplora");
        btnEsplora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEsplora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsplora.setMaximumSize(new java.awt.Dimension(83, 92));
        btnEsplora.setMinimumSize(new java.awt.Dimension(83, 92));
        btnEsplora.setPreferredSize(new java.awt.Dimension(83, 92));
        btnEsplora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsploraActionPerformed(evt);
            }
        });

        btnCibo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCibo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCibo.setMaximumSize(new java.awt.Dimension(80, 80));
        btnCibo.setMinimumSize(new java.awt.Dimension(80, 80));
        btnCibo.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiboActionPerformed(evt);
            }
        });

        lblCibo.setForeground(new java.awt.Color(255, 255, 255));
        lblCibo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCibo.setText("jLabel6");

        btnAcqua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAcqua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAcqua.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAcqua.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAcqua.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAcqua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcquaActionPerformed(evt);
            }
        });

        lblAcqua.setForeground(new java.awt.Color(255, 255, 255));
        lblAcqua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAcqua.setText("jLabel6");

        btnMedicine.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMedicine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMedicine.setMaximumSize(new java.awt.Dimension(80, 80));
        btnMedicine.setMinimumSize(new java.awt.Dimension(80, 80));
        btnMedicine.setPreferredSize(new java.awt.Dimension(80, 80));
        btnMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineActionPerformed(evt);
            }
        });

        lblMedicine.setForeground(new java.awt.Color(255, 255, 255));
        lblMedicine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicine.setText("jLabel6");

        btnSalva.setBackground(new java.awt.Color(51, 153, 0));
        btnSalva.setFont(new java.awt.Font("Stencil", 0, 10)); // NOI18N
        btnSalva.setForeground(new java.awt.Color(255, 255, 255));
        btnSalva.setText("salva");
        btnSalva.setActionCommand("");
        btnSalva.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaActionPerformed(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carovana.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(42, 42, 42)
                        .addComponent(lblFame, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addComponent(lblSete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(lblAttaco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(pgbSalute, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pgbMappa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTime, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(lblDays, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(slpEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnEsplora, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCibo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAcqua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAcqua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSalva, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pgbSalute, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(lblDays)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblFame)
                            .addComponent(jLabel3)
                            .addComponent(lblSete)
                            .addComponent(jLabel5)
                            .addComponent(lblAttaco)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTime)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pgbMappa, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEsplora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblMedicine)
                                            .addComponent(btnSalva)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCibo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCibo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAcqua, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(21, 21, 21)
                                        .addComponent(lblAcqua))))
                            .addComponent(slpEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCiboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiboActionPerformed
        gameManager.mangia();
        setDati();
    }//GEN-LAST:event_btnCiboActionPerformed

    private void btnEsploraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsploraActionPerformed
        ttaEvento.append(esplora() + "\n");
        if (!gameManager.check()) {
            JOptionPane.showMessageDialog(null, "Sei Morto!", "Fallimento", JOptionPane.INFORMATION_MESSAGE);
            btnEsplora.setEnabled(false);
            btnSalva.setEnabled(false);
        }
    }//GEN-LAST:event_btnEsploraActionPerformed

    private void btnAcquaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcquaActionPerformed
        gameManager.bere();
        setDati();
    }//GEN-LAST:event_btnAcquaActionPerformed

    private void btnMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineActionPerformed
        gameManager.cura();
        setDati();
    }//GEN-LAST:event_btnMedicineActionPerformed

    private void btnSalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaActionPerformed
        fs.setWrite(true);
        fs.setGameManager(gameManager);
        fs.setVisible(true);
    }//GEN-LAST:event_btnSalvaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcqua;
    private javax.swing.JButton btnCibo;
    private javax.swing.JButton btnEsplora;
    private javax.swing.JButton btnMedicine;
    private javax.swing.JButton btnSalva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAcqua;
    private javax.swing.JLabel lblAttaco;
    private javax.swing.JLabel lblCibo;
    private javax.swing.JLabel lblDays;
    private javax.swing.JLabel lblFame;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblSete;
    private javax.swing.JLabel lblTime;
    private javax.swing.JProgressBar pgbMappa;
    private javax.swing.JProgressBar pgbSalute;
    private javax.swing.JScrollPane slpEvento;
    private javax.swing.JTextArea ttaEvento;
    // End of variables declaration//GEN-END:variables
}
