/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progetto.gdr;

import javax.swing.ImageIcon;

/**
 *
 * @author zxt02
 */
public class FormIstruzione extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormIstruzione.class.getName());
    private int click;

    /**
     * Creates new form Istruzione
     */
    public FormIstruzione() {
        initComponents();
        click = 0;
        setTesto();
    }
    
    public void setTesto(){
        switch(click){
            case 0:
               txtaTesto.setText("In un mondo devastato dalla guerra, le città sono ridotte in rovine e le risorse sono estremamente scarse.   Sei un sopravvissuto costretto a intraprendere un viaggio nell’ignoto.\n"
                + "In questa terra desolata dovrai esplorare, raccogliere risorse e affrontare eventi casuali e pericoli continui.   Fame, sete, nemici e condizioni estreme metteranno alla prova la tua sopravvivenza.\n"
                + "\nHai un solo obiettivo: sopravvivere per 30 giorni e raggiungere un rifugio sicuro.\n"
                + "Ogni scelta può determinare la tua vita o la tua morte.");
                btnNext.setEnabled(true);
                btnBack.setEnabled(false);
                lblImage.setIcon(new ImageIcon(getClass().getResource("/images/step1.png")));
               break;
            case 1:
                txtaTesto.setText("Premendo il pulsante “Esplora”, eseguirai un’azione e verrà attivato un evento casuale. Potrai trovare risorse, incontrare nemici o affrontare pericoli imprevisti.\n"
                        + "Ogni volta che premi “Esplora”, il tempo avanza. Un giorno corrisponde a quattro azioni di esplorazione.\n"
                        + "Gestisci attentamente le tue scelte per sopravvivere e continuare il viaggio verso il rifugio.");
                btnNext.setEnabled(true);
                btnBack.setEnabled(true);
                lblImage.setIcon(new ImageIcon(getClass().getResource("/images/step2.png")));
                break;
            case 2:
                txtaTesto.setText("Fame / Sete\n"
                        + "Quando il livello di fame o sete supera 30, il personaggio inizia a perdere salute nel tempo. Più il valore è alto, maggiore sarà la perdita. È importante trovare cibo e acqua per sopravvivere.\n"
                        + "\n"
                        + "Attacco\n"
                        + "Il valore di attacco determina l’efficacia in combattimento. Quando incontri un nemico, un attacco alto aumenta le possibilità di vittoria e di ottenere risorse; se è troppo basso, sarai costretto a fuggire subendo danni.");
                btnNext.setEnabled(true);
                btnBack.setEnabled(true);
                lblImage.setIcon(new ImageIcon(getClass().getResource("/images/step3.png")));
                break;
            case 3:
                txtaTesto.setText("Bottone Acqua\n"
                        + "Premendo questo pulsante puoi usare l’acqua disponibile per ridurre il livello di sete e mantenere la sopravvivenza.\n"
                        + "\n"
                        + "Bottone Cibo\n"
                        + "Premendo questo pulsante puoi usare il cibo disponibile per ridurre la fame e recuperare energia.\n"
                        + "\n"
                        + "Bottone Medicina\n"
                        + "Premendo questo pulsante puoi usare le medicine per recuperare salute e resistere ai danni o alle malattie.");
                btnNext.setEnabled(true);
                btnBack.setEnabled(true);
                lblImage.setIcon(new ImageIcon(getClass().getResource("/images/step4.png")));
                break;
            case 4:
                txtaTesto.setText("Pulsante Salva\n"
                        + "Premendo questo pulsante puoi salvare i progressi di gioco.\n"
                        + "\n"
                        + "Sono disponibili due modalità di salvataggio:\n"
                        + "Formato CSV – Facile da leggere e modificare manualmente.\n"
                        + "Formato SER – Serializzazione degli oggetti Java, per salvare e ripristinare lo stato completo del gioco.");
                btnNext.setEnabled(false);
                btnBack.setEnabled(true);
                lblImage.setIcon(new ImageIcon(getClass().getResource("/images/step5.png")));
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaTesto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel1.setText("Introduzione");

        btnBack.setBackground(new java.awt.Color(51, 153, 255));
        btnBack.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnNext.setBackground(new java.awt.Color(0, 204, 51));
        btnNext.setFont(new java.awt.Font("Stencil", 0, 12)); // NOI18N
        btnNext.setText("Next");
        btnNext.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        txtaTesto.setEditable(false);
        txtaTesto.setBackground(new java.awt.Color(255, 255, 255));
        txtaTesto.setColumns(20);
        txtaTesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtaTesto.setLineWrap(true);
        txtaTesto.setRows(5);
        txtaTesto.setToolTipText("");
        txtaTesto.setWrapStyleWord(true);
        txtaTesto.setAutoscrolls(false);
        txtaTesto.setBorder(null);
        jScrollPane1.setViewportView(txtaTesto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel2)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        click--;
        setTesto();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        click++;
        setTesto();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormIstruzione().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextArea txtaTesto;
    // End of variables declaration//GEN-END:variables
}
